import { Injectable, inject } from '@angular/core';
import { Observable, of } from 'rxjs';
import { map, catchError } from 'rxjs/operators';

import { DriverReputation } from '../domain/model/driver-reputation.entity';
import { PassengerReputation } from '../domain/model/passenger-reputation.entity';
import { TripRating } from '../domain/model/trip-rating.entity';

import { RatingAssembler } from './rating-assembler';
import { TrustReputationService } from '../../shared/infrastructure/api/generated/trust-reputation/trust-reputation.service';
import { TripRatingResponse, DriverReputationResponse, PassengerReputationResponse } from '../../shared/infrastructure/api/generated/model';

/**
 * @summary Infrastructure gateway to the Trust & Reputation Bounded Context.
 * Delegates all operations to the autogenerated Orval TrustReputationService.
 * @author Jesús Iván Castillo Vidal
 */
@Injectable({ providedIn: 'root' })
export class TrustReputationApiService {
  private trustReputationService = inject(TrustReputationService);

  // ── Reputation queries ─────────────────────────────────────────────────

  /**
   * Retrieves the aggregated reputation for a driver.
   *
   * @param driverId - The driver's ID.
   */
  getDriverReputation(driverId: string): Observable<DriverReputation> {
    return this.trustReputationService.getDriverReputation(driverId).pipe(
      map((res: DriverReputationResponse) => RatingAssembler.toDriverReputation(res))
    );
  }

  /**
   * Retrieves the aggregated reputation for a passenger.
   *
   * @param passengerId - The passenger's ID.
   */
  getPassengerReputation(passengerId: string): Observable<PassengerReputation> {
    return this.trustReputationService.getPassengerReputation(passengerId).pipe(
      map((res: PassengerReputationResponse) => RatingAssembler.toPassengerReputation(res))
    );
  }

  // ── Trip rating lookup ─────────────────────────────────────────────────

  /**
   * Retrieves the rating record for a specific trip.
   * If none exists or an error occurs, returns a fallback PENDING rating.
   *
   * @param tripId - The ride/trip ID.
   */
  getTripRating(tripId: string): Observable<TripRating> {
    return this.trustReputationService.getTripRating<TripRatingResponse>(tripId).pipe(
      map((res: TripRatingResponse) => RatingAssembler.toEntity(res)),
      catchError(() => {
        // ponytail: fallback if rating record is not created yet
        const fallback = new TripRating();
        fallback.tripId = tripId;
        fallback.openForRating();
        return of(fallback);
      })
    );
  }

  // ── Rating submissions ─────────────────────────────────────────────────

  /**
   * Submits a driver rating for a given trip.
   */
  rateDriver(
    tripId: string,
    driverId: string,
    passengerId: string,
    score: number
  ): Observable<TripRating> {
    return this.trustReputationService.rateDriver<TripRatingResponse>(tripId, { score }).pipe(
      map((res: TripRatingResponse) => RatingAssembler.toEntity(res))
    );
  }

  /**
   * Submits a passenger rating for a given trip.
   */
  ratePassenger(
    tripId: string,
    driverId: string,
    passengerId: string,
    score: number,
    comment: string = ''
  ): Observable<TripRating> {
    return this.trustReputationService.ratePassenger<TripRatingResponse>(tripId, { score, comment }).pipe(
      map((res: TripRatingResponse) => RatingAssembler.toEntity(res))
    );
  }

  /**
   * Skips rating a driver for a trip.
   */
  skipDriverRating(
    tripId: string,
    driverId: string,
    passengerId: string
  ): Observable<TripRating> {
    return this.trustReputationService.skipDriverRating<TripRatingResponse>(tripId).pipe(
      map((res: TripRatingResponse) => RatingAssembler.toEntity(res))
    );
  }

  /**
   * Skips rating a passenger for a trip.
   */
  skipPassengerRating(
    tripId: string,
    driverId: string,
    passengerId: string
  ): Observable<TripRating> {
    return this.trustReputationService.skipPassengerRating<TripRatingResponse>(tripId).pipe(
      map((res: TripRatingResponse) => RatingAssembler.toEntity(res))
    );
  }
}
